/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aa;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author matte
 */
public class Card extends javax.swing.JPanel implements MouseListener {

    /**
     * Creates new form Card
     */
    int status;
    int cardId;
    JLabel backImage;
    String superPowerDescription;
    Image frontImage;
    String name;
    JLabel front_image;

    public Card(int card_id, String description) throws IOException {
        super.addMouseListener(this);
        initComponents();
        this.status = 0; //back:0, front:1, taken:2
        this.cardId = card_id;  // reference to outer array with all details
        this.superPowerDescription = description;
        this.name = GamePanel.namesMatrix[cardId % 20];
        this.front_image = loadImage();
        //this.Front.image = ...
    }
//super prova epica 2
    public void turnCardUp() {
        cardBackBtn.setVisible(false);
        status = 1;
        setLayout(new BorderLayout());
        add(this.front_image);
        Game.mp.setDescriptionLabel(this.superPowerDescription);
        Game.mp.setNameLabel(this.name);
        Game.numeroMosse += 1;
        Game.numeroMosseReali +=1;
        JLabel front_image_1 = createImageGivenId("ciao");
        Game.mp.refresh(front_image_1);
        int numeroMosse = Game.numeroMosse;
        if (numeroMosse % 3 == 0){
            Game.numeroMosseReali -=1;
            Game.gp.turnDownAll();
            turnCardUp();
            
        }
        
    }

    public void turnCardDown() {
        if (status == 1) {
            remove(this.front_image);
            cardBackBtn.setVisible(true);
            status = 0;
            Game.mp.setDescriptionLabel("");
        }

    }

    public JLabel loadImage() {
        ImageIcon icon = createImageIcon("images/" + this.cardId % 20 + ".jpg", this.cardId+"");
        JLabel label1 = new JLabel("", icon, JLabel.CENTER);
        return label1;

        //add(label1);
    }
    
        public JLabel createImageGivenId(String id) {
        ImageIcon icon = createImageIcon("images/" + this.cardId % 20 + ".jpg", id);
        JLabel label1 = new JLabel("", icon, JLabel.CENTER);
        return label1;

        //add(label1);
    }

    protected ImageIcon createImageIcon(String path,
            String description) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL, description);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardBackBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(90, 119));

        cardBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aa/card_back.png"))); // NOI18N
        cardBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cardBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardBackBtnActionPerformed
        turnCardUp();
    }//GEN-LAST:event_cardBackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cardBackBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        turnCardDown();

    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //To change body of generated methods, choose Tools | Templates.
    }
}
