/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aa;

/**
 *
 * @author matte
 */
public class EndPanel extends javax.swing.JPanel {

    /**
     * Creates new form EndPanel
     */
    public EndPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstLabel = new javax.swing.JLabel();
        secondPointLabel = new javax.swing.JLabel();
        thirdPointsLabel = new javax.swing.JLabel();
        fourthPointsLabel = new javax.swing.JLabel();
        firstNumber = new javax.swing.JLabel();
        firstPointsLabel = new javax.swing.JLabel();
        secondNumber = new javax.swing.JLabel();
        thirdNumber = new javax.swing.JLabel();
        fourthNumber = new javax.swing.JLabel();
        secondLabel = new javax.swing.JLabel();
        thirdLabel = new javax.swing.JLabel();
        fourthLabel = new javax.swing.JLabel();
        playAgainButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        firstLabel.setBackground(new java.awt.Color(232, 186, 19));
        firstLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        firstLabel.setForeground(new java.awt.Color(232, 186, 19));
        firstLabel.setText("Player");
        firstLabel.setToolTipText("");
        firstLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        secondPointLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        secondPointLabel.setForeground(new java.awt.Color(186, 183, 171));
        secondPointLabel.setText("0");

        thirdPointsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        thirdPointsLabel.setForeground(new java.awt.Color(181, 109, 0));
        thirdPointsLabel.setText("0");

        fourthPointsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fourthPointsLabel.setText("0");

        firstNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        firstNumber.setForeground(new java.awt.Color(232, 186, 19));
        firstNumber.setText("1°");

        firstPointsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        firstPointsLabel.setForeground(new java.awt.Color(232, 186, 19));
        firstPointsLabel.setText("0");

        secondNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        secondNumber.setForeground(new java.awt.Color(186, 183, 171));
        secondNumber.setText("2°");

        thirdNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        thirdNumber.setForeground(new java.awt.Color(181, 109, 0));
        thirdNumber.setText("3°");

        fourthNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fourthNumber.setText("4°");

        secondLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        secondLabel.setForeground(new java.awt.Color(186, 183, 171));
        secondLabel.setText("Player");
        secondLabel.setToolTipText("");
        secondLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        thirdLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        thirdLabel.setForeground(new java.awt.Color(181, 109, 0));
        thirdLabel.setText("Player");
        thirdLabel.setToolTipText("");
        thirdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        fourthLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        fourthLabel.setText("Player");
        fourthLabel.setToolTipText("");
        fourthLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        playAgainButton.setText("RIGIOCA");
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });

        homeButton.setText("MENU PRINCIPALE");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        quitButton.setText("ABBANDONA");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fourthNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fourthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fourthPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstPointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondPointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(playAgainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNumber)
                    .addComponent(firstLabel)
                    .addComponent(firstPointsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondNumber)
                    .addComponent(secondLabel)
                    .addComponent(secondPointLabel))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thirdLabel)
                    .addComponent(thirdNumber)
                    .addComponent(thirdPointsLabel))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourthNumber)
                    .addComponent(fourthLabel)
                    .addComponent(fourthPointsLabel))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playAgainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playAgainButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel firstNumber;
    private javax.swing.JLabel firstPointsLabel;
    private javax.swing.JLabel fourthLabel;
    private javax.swing.JLabel fourthNumber;
    private javax.swing.JLabel fourthPointsLabel;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel secondLabel;
    private javax.swing.JLabel secondNumber;
    private javax.swing.JLabel secondPointLabel;
    private javax.swing.JLabel thirdLabel;
    private javax.swing.JLabel thirdNumber;
    private javax.swing.JLabel thirdPointsLabel;
    // End of variables declaration//GEN-END:variables
}
