/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aa;

import static aa.Game.gp;
import static aa.Game.mp;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author matte
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game1
     */
    static MenuPanel mp; static int numeroMosse = 0; static GamePanel gp; static int numeroMosseReali = 0;
    
    public Game() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        getContentPane().setBackground(Costants.mainColor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartGameBtn = new javax.swing.JButton();
        pName1 = new javax.swing.JTextField();
        pName2 = new javax.swing.JTextField();
        pName3 = new javax.swing.JTextField();
        pName4 = new javax.swing.JTextField();
        instructions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StartGameBtn.setBackground(new java.awt.Color(255, 255, 255));
        StartGameBtn.setText("AVVIA GIOCO");
        StartGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameBtnActionPerformed(evt);
            }
        });

        pName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pName1ActionPerformed(evt);
            }
        });

        pName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pName2ActionPerformed(evt);
            }
        });

        pName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pName3ActionPerformed(evt);
            }
        });

        pName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pName4ActionPerformed(evt);
            }
        });

        instructions.setText("Inserisci il nome dei giocatori, se non desisderi aggiungerli tutti lascia vuota la casella di testo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(StartGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instructions)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pName1)
                                .addComponent(pName3)
                                .addComponent(pName4)
                                .addComponent(pName2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(505, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(instructions)
                .addGap(33, 33, 33)
                .addComponent(pName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(StartGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameBtnActionPerformed
        // TODO add your handling code here:
        StartGameBtn.setVisible(false);
        pName1.setVisible(false);
        pName2.setVisible(false);
        pName3.setVisible(false);
        pName4.setVisible(false);
        instructions.setVisible(false);
        setMenuPanel();
        setGamePanel();

    }//GEN-LAST:event_StartGameBtnActionPerformed

    private void pName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pName1ActionPerformed

    private void pName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pName2ActionPerformed

    private void pName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pName3ActionPerformed

    private void pName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pName4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    
    public void setGamePanel(){
        gp = new GamePanel(); 
        gp.setSize(1200, 700);
        gp.setBounds(50, 50, 1100, 700);
        this.getContentPane().add(gp);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
}
    public void setMenuPanel (){
        mp = new MenuPanel(createPlayers());
        mp.setBounds(1100, 50, 400, 700);
        this.add(mp);
     
    }
    
    public Player[] createPlayers(){
        int players = 0;
        if (!pName1.getText().isEmpty()){
            players++;
        }
        if (!pName2.getText().isEmpty()){
            players++;
        }
        if (!pName3.getText().isEmpty()){
            players++;
        }
        if (!pName4.getText().isEmpty()){
            players++;
        }
        JTextField[] x = {pName1, pName2, pName3, pName4};
        Player[] y = new Player[players];
        for (int i=0; i<players; i++){
            y[i] = new Player(x[i].getText());
        }
        return y;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StartGameBtn;
    private javax.swing.JLabel instructions;
    private javax.swing.JTextField pName1;
    private javax.swing.JTextField pName2;
    private javax.swing.JTextField pName3;
    private javax.swing.JTextField pName4;
    // End of variables declaration//GEN-END:variables
}
