/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aa;

import static aa.Game.gp;
import static aa.Game.mp;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.AbstractBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;


/**
 *
 * @author matte
 */

@SuppressWarnings("serial")

public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game1
     */
    static MenuPanel mp; static int numeroMosse = 0; static GamePanel gp; static int numeroMosseReali = 0;  static EndPanel ep; ArrayList<JTextField> players = new ArrayList<>();

    public Game() {
        UIManager.put("TextField.background", Color.WHITE);
        UIManager.put("TextField.border", BorderFactory.createCompoundBorder(
        new CustomeBorder(), 
        new EmptyBorder(new Insets(4,4,4,4))));
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        getContentPane().setBackground(Costants.mainColor);
        addPlayerField();
        this.getRootPane().setDefaultButton(StartGameBtn);
        
        /*pName2.setVisible(false);
        pName1.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                System.out.println("clicked");
            }
        });*/
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartGameBtn = new javax.swing.JButton();
        instructions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StartGameBtn.setBackground(new java.awt.Color(255, 255, 255));
        StartGameBtn.setText("AVVIA GIOCO");
        StartGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameBtnActionPerformed(evt);
            }
        });

        instructions.setText("Inserisci il nome dei giocatori, se non desisderi aggiungerli tutti lascia vuota la casella di testo");
        instructions.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StartGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(instructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(StartGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameBtnActionPerformed
        StartGameBtn.setVisible(false);
        instructions.setVisible(false);
        hidePlayerFields();
        setMenuPanel();
        setGamePanel();
    }//GEN-LAST:event_StartGameBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Game g = new Game();
                g.setVisible(true);
            }
        });
    }

    
    private void setGamePanel(){
        gp = new GamePanel(); 
        gp.setSize(1200, 700);
        gp.setBounds(50, 50, 1100, 700);
        this.getContentPane().add(gp);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
}
    
    private void setMenuPanel (){
        mp = new MenuPanel(createPlayers());
        mp.setBounds(1100, 50, 400, 700);
        this.add(mp);
    }
    
    private void setEndPanel(){
        ep = new EndPanel(); 
        ep.setSize(1200, 700);
        ep.setBounds(50, 50, 1100, 700);
        this.getContentPane().add(ep);
    }
    

    public Player[] createPlayers(){
        for (Object i: this.players.toArray()){
            JTextField t = (JTextField) i;
            if (t.getText().isEmpty()){
                this.players.remove(t);
            }
        }
        Object[] textFields =  this.players.toArray();
        Player[] players = new Player[textFields.length];
        for (int i=0; i<textFields.length; i++){
            JTextField tF = (JTextField) textFields[i];
            players[i] = new Player(tF.getText());
        }
        return players;
    }
    
    public void hidePlayerFields(){
        for (Object i: this.players.toArray()){
            JTextField t = (JTextField) i;
            t.setVisible(false);
        }
    }
    public void addPlayerField(){
        JTextField t = createJTextField(this.players.size());
        this.players.add(t);
    }
    
    
    public JTextField createJTextField(int id){
        JTextField tF = new JTextField();
        tF.setPreferredSize(new Dimension(90, 40));
        tF.setBounds(100, 200 + id * 50, 90, 40);
        tF.setBorder(new LineBorder(Costants.mainColor, 2));
        
        tF.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
               addPlayerField();
               System.out.println("entraato");
            }
        });
        
        this.add(tF);
        this.repaint();
        return tF;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StartGameBtn;
    private javax.swing.JLabel instructions;
    // End of variables declaration//GEN-END:variables
}
