/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aa;

import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author matte
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form CardBack
     */
    static MenuPanel mp; static int numeroMosse = 0; static GamePanel gp; static int numeroMosseReali = 0;
    public Game() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        getContentPane().setBackground(Costants.mainColor);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ca = new javax.swing.JButton();
        StartGameBtn = new javax.swing.JButton();

        Ca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aa/images/card_back.jpg"))); // NOI18N
        Ca.setAlignmentY(0.0F);
        Ca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ca.setHideActionText(true);
        Ca.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        Ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(133, 200, 242));

        StartGameBtn.setBackground(new java.awt.Color(255, 255, 255));
        StartGameBtn.setText("AVVIA GIOCO");
        StartGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(554, 554, 554)
                .addComponent(StartGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(587, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(StartGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //private Button StartGameButton = 
    private void CaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaActionPerformed

      
    private void StartGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameBtnActionPerformed
        // TODO add your handling code here:
        StartGameBtn.setVisible(false);
        setMenuPanel();
        setGamePanel();
        
    }//GEN-LAST:event_StartGameBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    
    public void setGamePanel(){
        gp = new GamePanel(); 
        gp.setSize(1200, 700);
        gp.setBounds(50, 50, 1100, 700);
        this.getContentPane().add(gp);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
}
    public void setMenuPanel (){
        mp = new MenuPanel();
        mp.setBounds(1100, 50, 400, 700);
        this.add(mp);
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ca;
    private javax.swing.JButton StartGameBtn;
    // End of variables declaration//GEN-END:variables
}
