/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aa;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;

/**
 *  
 * @author matte
 */
public class MenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    JLabel cardLabel = new JLabel();
    public MenuPanel() {
        initComponents();
        setBackground(Costants.mainColor);
        this.setBorder(new LineBorder(Costants.secondaryColor, 3));
    }
    
    public void setDescriptionLabel(String text){
        descriptionLabel.setText("<html>"+text+"</html>");

    }
    
    public void setNameLabel(String text){
        nameLabel.setText(text);
    }
    
    public void refresh(JLabel label){
        remove(this.cardLabel);
        setLabel(label);
        this.cardLabel = label;
        numeroMosseLabel.setText(Game.numeroMosseReali+"");
        
    }
    
    public void setLabel(JLabel label){
        setLayout(new BorderLayout());
        add(label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        numeroMosseLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        descriptionLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("Descrizione");

        numeroMosseLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        numeroMosseLabel.setText("Numero mosse");
        numeroMosseLabel.setToolTipText("");
        numeroMosseLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        nameLabel.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(numeroMosseLabel)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(nameLabel)
                .addGap(38, 38, 38)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(numeroMosseLabel)
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel numeroMosseLabel;
    // End of variables declaration//GEN-END:variables
}
